/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Admin: () => import('#controllers/admin_controller'),
  Articles: () => import('#controllers/articles_controller'),
  Blog: () => import('#controllers/blog_controller'),
  Geocoding: () => import('#controllers/geocoding_controller'),
  Session: () => import('#controllers/session_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
