/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ArticleSchema extends BaseModel {
  static $columns = ['content', 'coverImage', 'createdAt', 'excerpt', 'id', 'latitude', 'locationName', 'longitude', 'publishedAt', 'slug', 'title', 'updatedAt', 'userId'] as const
  $columns = ArticleSchema.$columns
  @column()
  declare content: string
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excerpt: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number | null
  @column()
  declare locationName: string | null
  @column()
  declare longitude: number | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SubscriberSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'email', 'id', 'updatedAt'] as const
  $columns = SubscriberSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
