/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ArticleSchema extends BaseModel {
  static $columns = ['content', 'coverImage', 'createdAt', 'excerpt', 'id', 'latitude', 'locationName', 'longitude', 'publishedAt', 'slug', 'title', 'updatedAt', 'userId'] as const
  $columns = ArticleSchema.$columns
  @column()
  declare content: string
  @column()
  declare coverImage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excerpt: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number | null
  @column()
  declare locationName: string | null
  @column()
  declare longitude: number | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PeriscopeEntrySchema extends BaseModel {
  static $columns = ['application', 'batchId', 'content', 'createdAt', 'familyHash', 'sequence', 'shouldDisplayOnIndex', 'tags', 'type', 'uuid'] as const
  $columns = PeriscopeEntrySchema.$columns
  @column()
  declare application: string
  @column()
  declare batchId: string
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare familyHash: string | null
  @column()
  declare sequence: string
  @column()
  declare shouldDisplayOnIndex: number
  @column()
  declare tags: string
  @column()
  declare type: string
  @column({ isPrimary: true })
  declare uuid: string
}

export class PeriscopeEntryTagSchema extends BaseModel {
  static $columns = ['entryUuid', 'tag'] as const
  $columns = PeriscopeEntryTagSchema.$columns
  @column({ isPrimary: true })
  declare entryUuid: string
  @column()
  declare tag: string
}

export class PeriscopeFlagSchema extends BaseModel {
  static $columns = ['expiresAt', 'name', 'value'] as const
  $columns = PeriscopeFlagSchema.$columns
  @column()
  declare expiresAt: bigint | number | null
  @column({ isPrimary: true })
  declare name: string
  @column()
  declare value: string
}

export class PeriscopeMonitoredTagSchema extends BaseModel {
  static $columns = ['tag'] as const
  $columns = PeriscopeMonitoredTagSchema.$columns
  @column({ isPrimary: true })
  declare tag: string
}

export class SubscriberSchema extends BaseModel {
  static $columns = ['active', 'createdAt', 'email', 'id', 'updatedAt'] as const
  $columns = SubscriberSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
